name: Monitor Pull Requests

on:
  schedule:
    - cron: '*/10 * * * *'  # Executa a cada 10 minutos
  workflow_dispatch: # Permite rodar manualmente

jobs:
  monitor_pull_requests:
    runs-on: ubuntu-latest
    steps:
    - name: Verificar Pull Requests abertas
      uses: actions/github-script@v6
      with:
        script: |
          const pullRequests = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open'
          });

          const now = new Date();
          const staleDuration = 5 * 60 * 1000; // 5 minutos em milissegundos

          for (const pr of pullRequests.data) {
            const createdAt = new Date(pr.created_at);
            if ((now - createdAt) > staleDuration) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: ['stale']
              });

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: 'Este pull request está aberto há mais de 5 minutos. Por favor, revise-o ou feche-o.'
              });
            }
          }
